### PR TITLE
Opening Closing animation

### LINKED ISSUE #1: Accordion opening and closing animation
The accordion just toggles the visibility of the text for now. It would be great if the text has a sliding down animation on being visible, and a sliding up animation on being dismissed.

Check line 152 of [Accordion.kt](https://github.com/gouravkhunger/AccoLib/blob/main/accolib/src/main/java/com/gouravkhunger/accolib/widget/Accordion.kt#L152) file

### PR DESCRIPTION
**Pull request by xtanion**
Fixes #1

### CODE REVIEW

**Comment by xtanion** [comment]
@gouravkhunger  have a look at the animations now 

https://user-images.githubusercontent.com/74976752/135765062-41674a3c-51cc-4031-8dac-768e6d789ade.mp4

**Comment by gouravkhunger** [comment]
Amazing work man!
How did you achieve this?

**Comment by xtanion** [comment]
Ahh, it was really simple actually, we don't need to write an animation explicitly for this. Just change the linear layout and added `android:animateLayoutChanges="true"` and worked perfectly fine.

**Comment by xtanion** [comment]
Now, can I get a merge XD

**Comment by gouravkhunger** [comment]
Oh 😂😂
This was the reason we were getting dual animations, one for the xml animation definition, and other from the code. 

Damn didn't give it a thought while building. Thanks a lot for fixing! Merging it :)

**Review by gouravkhunger — APPROVED** [review]

**Comment by gouravkhunger** [comment]
We'll will release a new version on jitpack when we add a few more changes :)

**Comment by xtanion** [comment]
Thanks for the merge, Glad to work on the project.

**Pull request merged**
